{{- if and  (not .Values.database.secrets) (not .Values.postgresql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "distribution.fullname" . }}-database-creds
  labels:
    app: {{ template "distribution.name" . }}
    chart: {{ template "distribution.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.distribution.name }}
type: Opaque
data:
  {{- if .Values.database.url }}
  db-url: {{ .Values.database.url | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.user }}
  db-user: {{ .Values.database.user | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.password }}
  db-password: {{ .Values.database.password | b64enc | quote }}
  {{- end }}
{{- end }}
