apiVersion: v1
kind: Secret
metadata:
  name: {{ template "distribution.fullname" . }}
  labels:
    app: {{ template "distribution.name" . }}
    chart: {{ template "distribution.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if and .Values.distribution.masterKey (not .Values.distribution.masterKeySecretName) }}
  master-key: {{ .Values.distribution.masterKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.distribution.joinKey (not .Values.distribution.joinKeySecretName) }}
  join-key: {{ .Values.distribution.joinKey | b64enc | quote }}
  {{- end }}
