apiVersion: v1
kind: Secret
metadata:
  name: {{ template "distribution.fullname" . }}
  labels:
    app: {{ template "distribution.name" . }}
    chart: {{ template "distribution.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if and .Values.distribution.masterKey (not .Values.distribution.masterKeySecretName) }}
  master-key: {{ .Values.distribution.masterKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.distribution.joinKey (not .Values.distribution.joinKeySecretName) }}
  join-key: {{ .Values.distribution.joinKey | b64enc | quote }}
  {{- end }}
{{- if not .Values.redis.existingSecret -}}
  {{- if .Values.redis.password }}
  redis-password:  {{ .Values.redis.password | b64enc | quote }}
  {{- else }}
  redis-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end -}}
