# CI values for Mission-control.

# If this is an upgrade over an existing Mission Control 4.x, explicitly pass 'unifiedUpgradeAllowed=true' to upgrade
unifiedUpgradeAllowed: true
missionControl:
  jfrogUrl: http://artifactory-artifactory.rt:8082

postgresql:
  postgresqlPassword: password
  db:
    password: password

