# CI values for Mission-control.

# rbac:
#   create: false
#
# serviceAccount:
#   create: false

missionControl:
  loggers:
    - jfmc-server.log
    - http.log

insightServer:
  loggers:
    - insight-server.log

insightScheduler:
  loggers:
    - insight-scheduler.log

insightExecutor:
  loggers:
    - insight-executor.log

postgresql:
  postgresPassword: postgres
  db:
    jfisPassword: password
    jfscPassword: password
    jfexPassword: password
    jfmcPassword: password
