# CI values for Xray

# rbac:
#   create: false
#
# serviceAccount:
#   create: false

xray:
  jfrogUrl: http://artifactory-artifactory.rt:8082

postgresql:
  postgresDatabase: xraydb
  postgresUser: xray
  postgresqlPassword: xray
  persistence:
    enabled: false

rabbitmq-ha:
  rabbitmqUsername: guest
  rabbitmqPassword: guest
  persistentVolume:
    enabled: false
