# CI values for Xray

analysis:
  loggers:
    - xray_analysis.log

indexer:
  loggers:
    - xray_indexer.log
  persistence:
    enabled: true

persist:
  loggers:
    - xray_persist.log

server:
  loggers:
    - xray_server.log
  persistence:
    enabled: true

postgresql:
  postgresDatabase: xraydb
  postgresUser: xray
  postgresPassword: xray
  persistence:
    enabled: true

mongodb:
  persistence:
    enabled: false
  mongodbRootPassword: password
  mongodbUsername: xray
  mongodbPassword: password
  mongodbDatabase: xray

rabbitmq-ha:
  rabbitmqUsername: guest
  rabbitmqPassword: guest
  persistentVolume:
    enabled: true
