{{- if not .Values.database.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mission-control.fullname" . }}-database-creds
  labels:
    app: {{ template "mission-control.name" . }}
    chart: {{ template "mission-control.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  {{- if .Values.postgresql.db.password }}
  db-password: {{ .Values.postgresql.db.password | b64enc | quote }}
  {{- else }}
  db-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- else }} 
  {{- if .Values.database.url }}
  db-url: {{ .Values.database.url | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.user }}
  db-user: {{ .Values.database.user | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.password }}
  db-password: {{ .Values.database.password | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
