apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mission-control.fullname" . }}-db-cred
  labels:
    app: {{ template "mission-control.name" . }}
    chart: {{ template "mission-control.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
{{- if and .Values.database.type (not (.Values.postgresql.enabled)) }}
  {{- if .Values.database.password }}
  jfmcPassword: {{ .Values.database.password | b64enc | quote }}
  jfisPassword: {{ .Values.database.password | b64enc | quote }}
  jfscPassword: {{ .Values.database.password | b64enc | quote }}
  jfexPassword: {{ .Values.database.password | b64enc | quote }}
  {{- else }}
    {{- if .Values.database.jfmcPassword }}
  jfmcPassword: {{ .Values.database.jfmcPassword | b64enc | quote }}
    {{- end }}
    {{- if .Values.database.jfisPassword }}
  jfisPassword: {{ .Values.database.jfisPassword | b64enc | quote }}
    {{- end }}
    {{- if .Values.database.jfscPassword }}
  jfscPassword: {{ .Values.database.jfscPassword | b64enc | quote }}
    {{- end }}
    {{- if .Values.database.jfexPassword }}
  jfexPassword: {{ .Values.database.jfexPassword | b64enc | quote }}
    {{- end }}
    {{- end }}
{{- else }}
  {{- if .Values.postgresql.db.jfisPassword }}
  jfisPassword: {{ .Values.postgresql.db.jfisPassword | b64enc | quote }}
  {{- else }}
  jfisPassword: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.db.jfscPassword }}
  jfscPassword: {{ .Values.postgresql.db.jfscPassword | b64enc | quote }}
  {{- else }}
  jfscPassword: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.db.jfexPassword }}
  jfexPassword: {{ .Values.postgresql.db.jfexPassword | b64enc | quote }}
  {{- else }}
  jfexPassword: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.db.jfmcPassword }}
  jfmcPassword: {{ .Values.postgresql.db.jfmcPassword | b64enc | quote }}
  {{- else }}
  jfmcPassword: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.postgresqlPassword }}
  postgres-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  {{- end }}
{{- end }}