apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mission-control.fullname" . }}
  labels:
    app: {{ template "mission-control.name" . }}
    chart: {{ template "mission-control.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if and .Values.missionControl.masterKey (not .Values.missionControl.masterKeySecretName) }}
  master-key: {{ .Values.missionControl.masterKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.missionControl.joinKey (not .Values.missionControl.joinKeySecretName) }}
  join-key: {{ .Values.missionControl.joinKey | b64enc | quote }}
  {{- end }}
