dependencies:
- name: postgresql
  version: 8.4.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: redis
  version: 10.5.6
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: redis.enabled
- name: rabbitmq
  version: 6.17.5
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: rabbitmq.enabled
