dependencies:
- name: postgresql
  version: 8.7.3
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 10.6.3
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: rabbitmq
  version: 6.25.0
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enabled
