{{- if .Values.buildPlane.k8s.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipelines.fullname" . }}-k8s-node
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
    component: k8s-node
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: node
      port: 30300
      protocol: TCP  
  selector:
    {{- include "pipelines.selectorLabels" . | nindent 4 }}
    component: k8s-node
{{- end }}
