apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipelines.services.name" . }}-headless
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.pipelines.api.service.port }}
{{- if eq .Values.pipelines.api.service.type "NodePort" }}
      nodePort: 30000
{{- end }}
      targetPort: 30000
      protocol: TCP
      name: api
    - port: {{ .Values.pipelines.www.service.port }}
{{- if eq .Values.pipelines.www.service.type "NodePort" }}
      nodePort: 30001
{{- end }}
      targetPort: 30001
      protocol: TCP
      name: www
  selector:
    {{- include "pipelines.selectorLabels" . | nindent 4 }}
    component: {{ include "pipelines.services.name" . }}
