{{- if and (not .Values.global.vault.existingSecret) (not .Values.vault.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: root-vault-secret
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ tpl .Values.global.vault.token . | b64enc | quote }}
{{- end }}
