apiVersion: v1
name: distribution
home: https://jfrog.com/platform/
description: A Helm chart for JFrog Distribution
version: 6.1.4
appVersion: 2.4.1
sources:
- https://bintray.com/jfrog/product/distribution/view
- https://github.com/jfrog/charts
keywords:
- distribution
- jfrog
maintainers:
- name: amithins
- email: amithk@jfrog.com
  name: amithins
- email: daniele@jfrog.com
  name: danielezer
- email: eldada@jfrog.com
  name: eldada
- email: ramc@jfrog.com
  name: chukka
- email: rimasm@jfrog.com
  name: rimusz
icon: https://raw.githubusercontent.com/jfrog/charts/master/stable/distribution/logo/distribution-logo.png
