kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "artifactory.fullname" . }}-installer-info
  labels:
    app: {{ template "artifactory.name" . }}
    chart: {{ template "artifactory.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  installer-info.json: |
    {
      "productId": "{{ template "artifactory.chart" . }}",
      "features": [
      {
        "featureId": "AppVersion/{{ default .Chart.AppVersion .Values.artifactory.image.version }}"
      }
      ]
    }