{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "artifactory.name" . }}-fluentd-config
  labels:
    app: {{ template "artifactory.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  fluentd.conf: |
{{ tpl .Values.metrics.fluentd.fluentdConf . | indent 4 }}
{{- end -}}
