# CI values for Pipelines

pipelines:
  jfrogUrl: http://artifactory-artifactory.rt:8082
  jfrogUrlUI: http://artifactory-artifactory.rt:8082

  api:
    externalUrl: http://pipelines.test.com

  www:
    externalUrl: http://pipelines.test.com

  msg:
    uiUserPassword: password

postgresql:
  postgresqlPassword: password

rabbitmq:
  rabbitmq:
    password: password
