apiVersion: v1
name: xray
<<<<<<< HEAD
version: 0.10.1
=======
version: 0.10.0
>>>>>>> e8f619ac2335b9b91438f0e9b5308d8b620803c2
appVersion: 2.7.0
home: https://www.jfrog.com/xray/
description: Universal component scan for security and license inventory and impact analysis
keywords:
- xray
- jfrog
sources:
- https://bintray.com/jfrog/product/xray/view
- https://github.com/jfrog/charts
maintainers:
- name: eldada
  email: eldada@jfrog.com
- email: jainishs@jfrog.com
  name: jainishshah17
- email: rimasm@jfrog.com
  name: rimusz
icon: https://raw.githubusercontent.com/jfrog/artifactory-dcos/master/images/jfrog_med.png
