dependencies:
- name: postgresql
  version: 8.4.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: rabbitmq-ha
  version: 1.41.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: rabbitmq-ha.enabled
- name: rabbitmq
  version: 6.18.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: rabbitmq.enabled
