rabbitmq-ha:
  replicaCount: 4
  rabbitmqMemoryHighWatermark: 2000MB
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"
mongodb:
  resources:
    requests:
      memory: "12Gi"
      cpu: "1"
    limits:
      memory: "12Gi"
      cpu: "3"
  ## Make sure the --wiredTigerCacheSizeGB is
  ## no more than half the memory limit!
  ## This is critical to protect against
  ## OOMKill by Kubernetes!
  mongodbExtraFlags:
    - "--wiredTigerCacheSizeGB=6"
postgresql:
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "3Gi"
      cpu: "2"
server:
  replicaCount: 4
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"
analysis:
  replicaCount: 4
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"
persist:
  replicaCount: 4
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"
indexer:
  replicaCount: 4
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"
  persistence:
    size: 500Gi
