rabbitmq-ha:
  replicaCount: 2
  rabbitmqMemoryHighWatermark: 1000MB
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"
mongodb:
  resources:
    requests:
      memory: "6Gi"
      cpu: "500m"
    limits:
      memory: "6Gi"
      cpu: "1"
  ## Make sure the --wiredTigerCacheSizeGB is
  ## no more than half the memory limit!
  ## This is critical to protect against
  ## OOMKill by Kubernetes!
  mongodbExtraFlags:
    - "--wiredTigerCacheSizeGB=3"
postgresql:
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"
server:
  replicaCount: 2
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"
analysis:
  replicaCount: 2
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"
persist:
  replicaCount: 2
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"
indexer:
  replicaCount: 2
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"
  persistence:
    size: 100Gi
