# CI values for Distribution

# replicaCount: 2
# rbac:
#   create: false
#
# serviceAccount:
#   create: false

postgresql:
  postgresqlPassword: password
  persistence:
    enabled: false

redis:
  password: "password"
  persistence:
    enabled: false

distributor:
  persistence:
    enabled: false
  # loggers:
  #   - foreman.log

distribution:
  jfrogUrl: http://artifactory-artifactory.rt:8082
  persistence:
    enabled: false
  # loggers:
  #   - access.log
  #   - request.log
