apiVersion: v1
kind: Secret
metadata:
  name: {{ template "artifactory-ha.fullname" . }}
  labels:
    app: {{ template "artifactory-ha.name" . }}
    chart: {{ template "artifactory-ha.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if not (or .Values.artifactory.masterKey .Values.global.masterKey) }}
  {{- if not (or .Values.artifactory.masterKeySecretName .Values.global.masterKeySecretName) }}
  master-key: {{ required  "masterKey is required!" .Values.artifactory.masterKey }}
  {{- end }}
  {{- end }}
  {{- if or .Values.artifactory.masterKey .Values.global.masterKey }}
  {{- if not (or .Values.artifactory.masterKeySecretName .Values.global.masterKeySecretName) }}
  master-key: {{ include "artifactory.masterKey" . | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if or .Values.artifactory.joinKey .Values.global.joinKey }}
  {{- if not (or .Values.artifactory.joinKeySecretName .Values.global.joinKeySecretName) }}
  join-key: {{ include "artifactory.joinKey" . | b64enc | quote }}
  {{- end }}
  {{- end }}
