{{- if not .Values.nginx.customArtifactoryConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "artifactory-ha.fullname" . }}-nginx-artifactory-conf
  labels:
    app: {{ template "artifactory-ha.name" . }}
    chart: {{ template "artifactory-ha.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  artifactory.conf: |
{{ tpl .Values.nginx.artifactoryConf . | indent 4 }}
{{- end }}