artifactory:
  persistence:
    enabled: true

postgresql:
  postgresPassword: "password"
  postgresConfig:
    maxConnections: "102"
  persistence:
    enabled: false

nginx:
  enabled: false
  service:
    ## For minikube, set this to NodePort, elsewhere use LoadBalancer
    type: NodePort
