{{- if and .Values.global.postgresql.url (not .Values.postgresql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "xray.fullname" . }}-postgres-secret
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.global.postgresql.url }}
      postgresqlUrl: {{ .Values.global.postgresql.url | b64enc | quote }}
  {{- end }}
{{- end }}
