apiVersion: v1
kind: Secret
metadata:
  name: {{ template "xray.fullname" . }}
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if or .Values.xray.masterKey .Values.global.masterKey }}
  {{- if not (or .Values.xray.masterKeySecretName .Values.global.masterKeySecretName) }}
  master-key: {{ include "xray.masterKey" . | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if or .Values.xray.joinKey .Values.global.joinKey }}
  {{- if not (or .Values.xray.joinKeySecretName .Values.global.joinKeySecretName) }}
  join-key: {{ include "xray.joinKey" . | b64enc | quote }}
  {{- end }}
  {{- end }}
