{{- if index .Values "rabbitmq" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "xray.fullname" . }}-rabbitmq-load-definition
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  load_definition.json: |-
{{ tpl .Values.rabbitmq.definitions . | indent 4 }}
{{- end }}
