apiVersion: v1
kind: Service
metadata:
  name: {{ template "xray-server.fullname" . }}
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    component: {{ .Values.server.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.server.service.annotations }}
  annotations:
    {{- range $key, $value := .Values.server.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
  - port: {{ .Values.server.externalPort }}
    protocol: TCP
    name: http
    targetPort: {{ .Values.server.internalPort }}
  - port: 8082
    protocol: TCP
    name: router
    targetPort: 8082
  selector:
    app: {{ template "xray.name" . }}
    component: {{ .Values.server.name }}
    release: {{ .Release.Name }}
